apiVersion: apps/v1
kind: Deployment
metadata:
  name: polar-rabbitmq
  labels:
    db: polar-rabbitmq
spec:
  selector:
    matchLabels:
      db: polar-rabbitmq
  template:
    metadata:
      labels:
        db: polar-rabbitmq
    spec:
      containers:
      - name: polar-rabbitmq
        image: rabbitmq:3.12-management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: user
        - name: RABBITMQ_DEFAULT_PASS
          value: password


---


apiVersion: v1
kind: Service
metadata:
  name: polar-rabbitmq
  labels:
    db: polar-rabbitmq
spec:
  type: ClusterIP
  selector:
    db: polar-rabbitmq
  ports:
  - name: amqp
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: web
    protocol: TCP
    port: 15672
    targetPort: 15672
